spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/webknot}
spring.datasource.username=${DB_USER:likhithrajup}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}

spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA:dev}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoint.health.show-details=always
management.endpoint.prometheus.access=unrestricted
management.endpoint.health.access=unrestricted
management.endpoint.info.access=unrestricted

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

app.security.permit-open-legacy-endpoints=true
app.security.public-docs-enabled=true
